[package]
name = "mbtagger"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4", features = ["derive"] }
id3 = "1.4"
env_logger = "0.10"
log = "0.4"
