[package]
name = "mbtagger"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4", features = ["derive"] }
env_logger = "0"
log = "0"
thiserror = "1"
unidecode = "0"
levenshtein = "1"
musicbrainz_rs_nova = "0"
tokio = { version = "1", features = ["full"] }
id3 = { version = "1", optional = true }
metaflac = { version = "0", optional = true }
futures = "0"
hungarian = "1"

[dev-dependencies]
float_eq = "1"

[features]
default = ["flac", "id3"]
flac = ["dep:metaflac"]
id3 = ["dep:id3"]
