[package]
name = "mbtagger"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4", features = ["derive"] }
env_logger = "0.10"
log = "0.4"
thiserror = "1.0"
id3 = { version = "1.4", optional = true }
metaflac = { version = "0.2", optional = true }

[features]
default = ["flac", "id3"]
flac = ["dep:metaflac"]
id3 = ["dep:id3"]
