[lookup]
connection_limit = 10
release_candidate_limit = 5

[weights.track]
track_title = 3.0
track_artist = 3.0
track_number = 1.0
track_length = 1.0
musicbrainz_recording_id = 5.0

[weights.release]
release_title = 3.0
release_artist = 3.0
musicbrainz_release_id = 5.0
media_format = 1.0
record_label = 0.5
catalog_number = 0.5
barcode = 0.5
track_assignment = 1.0

[user_interface]
default_terminal_width = 80

[user_interface.candidate_details]
action_style = { foreground_color = "blue" }

[user_interface.candidate_details.string_diff_style]
present_style = {}
missing_style = { foreground_color = "grey", attributes = ["italic"] }
equal_style = {}
delete_style = { foreground_color = "red", attributes = ["bold"] }
insert_style = { foreground_color = "green", attributes = ["bold"] }
replace_old_style = { foreground_color = "yellow", attributes = ["bold"] }
replace_new_style = { foreground_color = "yellow", attributes = ["bold"] }
