[analyzers]
num_parallel_jobs = 0
# The chromaprint_fingerprint analyzer is disabled by default.
enabled = ["track_length"]

[lookup]
connection_limit = 10
release_candidate_limit = 5

[weights.track]
track_title = 3.0
track_artist = 3.0
track_number = 1.0
track_length = 1.0
musicbrainz_recording_id = 5.0

[weights.release]
release_title = 3.0
release_artist = 3.0
musicbrainz_release_id = 5.0
media_format = 1.0
record_label = 0.5
catalog_number = 0.5
barcode = 0.5
track_assignment = 1.0

[user_interface]
default_terminal_width = 80

[user_interface.candidate_details]
tracklist_indent = " * "
tracklist_separator = " -> "
tracklist_extra_indent = "   "
tracklist_extra_separator = "    "
tracklist_title_line_limit = 0
tracklist_artist_line_limit = 0
tracklist_extra_line_limit = 2
release_artist_and_title_style = { attributes = ["bold"] }
release_meta_style = { foreground_color = "grey" }
disc_title_style = { attributes = ["underlined"] }
track_number_style = {}
track_number_style_default = { foreground_color = "grey" }
track_length_changed_style = { foreground_color = "red", attributes = ["bold"] }
track_length_missing_style = { foreground_color = "grey" }
changed_value_style = { foreground_color = "yellow", attributes = ["bold"] }
action_style = { foreground_color = "blue" }
candidate_similarity_style = { attributes = ["bold"] }
candidate_similarity_prefix = " ("
candidate_similarity_prefix_style = { foreground_color = "grey" }
candidate_similarity_suffix = ")"
candidate_similarity_suffix_style = { foreground_color = "grey" }

[user_interface.candidate_details.unmatched_tracks_residual]
prefix = "  ! "
prefix_style = { foreground_color = "yellow", attributes = ["bold"] }
headline_style = { foreground_color = "yellow", attributes = ["underlined"] }
track_number_style = { foreground_color = "grey" }
track_title_style = { foreground_color = "yellow", attributes = ["bold"] }

[user_interface.candidate_details.unmatched_tracks_missing]
prefix = "  ? "
prefix_style = { foreground_color = "red", attributes = ["bold"] }
headline_style = { foreground_color = "red", attributes = ["underlined"] }
track_number_style = { foreground_color = "grey" }
track_title_style = { foreground_color = "red", attributes = ["bold"] }

[user_interface.candidate_details.string_diff_style]
present = {}
missing = { foreground_color = "grey", attributes = ["italic"] }
equal = {}
delete = { foreground_color = "red", attributes = ["bold"] }
insert = { foreground_color = "green", attributes = ["bold"] }
replace_old = { foreground_color = "yellow", attributes = ["bold"] }
replace_new = { foreground_color = "yellow", attributes = ["bold"] }
