---
name: Build
on: [push, pull_request]

jobs:
    cargo-toml-features:
        name: Generate Feature Combinations
        runs-on: ubuntu-latest
        outputs:
            feature-combinations: ${{ steps.cargo-toml-features.outputs.feature-combinations }}
        steps:
            - name: Check out repository
              uses: actions/checkout@v4
            - name: Determine Cargo Features
              id: cargo-toml-features
              uses: Holzhaus/cargo-toml-features-action@3afa751aae4071b2d1ca1c5fa42528a351c995f4

    build:
        needs: cargo-toml-features
        runs-on: ubuntu-latest
        strategy:
            matrix:
                features: ${{ fromJson(needs.cargo-toml-features.outputs.feature-combinations) }}
        env:
            CRATE_FEATURES: ${{ join(matrix.features, ',') }}
        steps:
            - name: Check out repository
              uses: actions/checkout@v4
            - name: Print Rust version
              run: rustc -vV
            - name: Build Package
              run: cargo publish --dry-run --locked --no-default-features --features "${CRATE_FEATURES}"
            - name: Run Tests
              run: cargo test --locked --no-default-features --features "${CRATE_FEATURES}"
            - name: Run Benchmark
              run: cargo bench --locked --no-default-features --features "${CRATE_FEATURES}"
            - name: Generate Documentation
              run: cargo doc --no-deps --locked --no-default-features --features "${CRATE_FEATURES}"

    publish:
        needs: build
        runs-on: ubuntu-latest
        if: startsWith(github.ref, 'refs/tags/')
        steps:
            - name: Check out repository
              uses: actions/checkout@v4
            - name: Publish Package
              run: cargo publish --locked
              env:
                  CARGO_REGISTRY_TOKEN: ${{ secrets.CRATES_IO_TOKEN }}
