---
name: Build
on: [push, pull_request]

jobs:
    generate-matrix:
        name: Generate Build Matrix
        runs-on: ubuntu-latest
        outputs:
            matrix: ${{ steps.set-matrix.outputs.matrix }}
        steps:
            - name: Check out repository
              uses: actions/checkout@v4
            - name: Set up Python
              uses: actions/setup-python@v5
              with:
                  python-version: '3.13'
            - name: Generate Build Matrix
              id: set-matrix
              run: python .github/generate_matrix.py Cargo.toml "$GITHUB_OUTPUT"

    build:
        needs: generate-matrix
        runs-on: ubuntu-latest
        strategy:
            matrix: ${{ fromJson(needs.generate-matrix.outputs.matrix) }}
        steps:
            - name: Check out repository
              uses: actions/checkout@v4
            - name: Print Rust version
              run: rustc -vV
            - name: Run tests
              run: cargo test --no-default-features --features "${{ matrix.features }}" --verbose
            - name: Run bench
              run: cargo bench --no-default-features --features "${{ matrix.features }}" --verbose
            - name: Run doc
              run: cargo doc --no-default-features --features "${{ matrix.features }}" --verbose
