---
name: Auto-merge Dependabot PR

on:
    pull_request:

permissions:
    contents: write
    pull-requests: write

jobs:
    auto-merge:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: ahmadnassri/action-dependabot-auto-merge@v2
              with:
                  target: major
                  github-token: ${{ github.token }}
